
export enum ContractStatus {
  Active = 'Active',       // 履约中
  Expiring = 'Expiring',   // 即将到期
  Terminated = 'Terminated', // 已退租
  Pending = 'Pending',     // 签约中
  Expired = 'Expired',     // 已到期(历史合同)
}

export enum UnitStatus {
  Vacant = 'Vacant',       // 空置
  Occupied = 'Occupied',   // 已租
  Reserved = 'Reserved',   // 预留
}

export enum DepositStatus {
  Unpaid = 'Unpaid',
  Paid = 'Paid',
  Refunded = 'Refunded',
  Deducted = 'Deducted', // 抵扣
}

export type PaymentCycle = 'Monthly' | 'Quarterly' | 'SemiAnnual' | 'Annual';

export interface RentFreePeriod {
  start: string;
  end: string;
  description: string;
}

export interface Unit {
  id: string;
  name: string; // e.g., 101, 102
  area: number;
  status: UnitStatus;
  floor: number;
  isSelfUse?: boolean;
}

export interface Building {
  id: string;
  name: string; // e.g., 1号楼
  type?: 'Building' | 'Site'; // 新增：区分楼宇或场地 (默认为 Building)
  units: Unit[];
}

export interface KeyMoment {
  id: string;
  date: string; // YYYY-MM-DD or YYYY-MM
  title: string;
  description: string;
  type: 'Anniversary' | 'Product' | 'News' | 'Award' | 'Other' | 'ParkAnniversary';
  sourceUrl?: string;
  isAutoGenerated?: boolean;
}

export interface Tenant {
  id: string;
  rootId?: string; // 根ID，用于关联同一个客户的历史续签记录
  name: string;
  contactInfo?: string;
  industry?: string;
  
  // Basic Info for Insights
  foundingDate?: string; // YYYY-MM-DD
  legalRepName?: string; // 法人/管理层姓名
  legalRepBirthday?: string; // MM-DD or YYYY-MM-DD
  contactName?: string; // 对接人姓名
  contactBirthday?: string; // MM-DD or YYYY-MM-DD

  // Link to Asset
  buildingId: string;
  unitIds: string[]; 
  totalArea: number;

  // Lease Terms
  signingDate?: string; // 新增：合同签约时间
  leaseStart: string;
  leaseEnd: string;
  /** 实际入驻日期（用于入园周年等关键时刻；未填时回退为起租日） */
  moveInDate?: string;

  // Rent
  unitPrice?: number; // Price per sqm per DAY
  monthlyRent: number; // Total monthly rent (calculated)
  
  rentFreePeriods: RentFreePeriod[];

  // Payment Terms
  paymentCycle: PaymentCycle;
  paymentCycleMonths?: number; // Flexible months input (e.g. 1, 3, 6, 12)
  firstPaymentDate: string;
  firstPaymentMonths?: number;
  
  // New: Billing Strategy (免租期处理方式)
  // 'Deduct': 当期账单扣除 - 在当期账单中扣除免租期月数，收款时间不变但金额减少
  // 'Defer': 账期顺延 - 免租期月份不产生账单，收款时间整体顺延
  freeRentHandling?: 'Deduct' | 'Defer';

  // Deposit
  depositAmount: number;
  depositStatus: DepositStatus;

  // Termination
  status: ContractStatus;
  terminationDate?: string;
  terminationType?: 'Normal' | 'Early';
  terminationReason?: string;
  
  // Special requirements
  specialRequirements?: string;
  
  // Risk Management
  isRisk?: boolean; // High risk flag

  // New: Parking
  // parkingSpaces field is deprecated in favor of specific fields below, but kept for legacy type safety if needed
  parkingSpaces?: number; 
  
  contractParkingSpaces?: number; // Contracted/Agreed number of spaces
  actualParkingSpaces?: number;   // Actually activated/paid spaces

  parkingUnitPrice?: number; // Price per space per month

  // New: Customer Insights
  keyMoments?: KeyMoment[];
}

export interface PaymentRecord {
  id: string;
  tenantId: string;
  tenantName: string;
  amount: number;
  type: 'Rent' | 'Deposit' | 'ManagementFee' | 'ParkingFee' | 'Other' | 'DepositToRent' | 'DepositRefund'; // Added ParkingFee
  date: string;
  /** 关联账期，支持单个或多个 YYYY-MM（逗号分隔），用于提前收款核销未来应收 */
  period?: string;
  status: 'Received' | 'Pending';
  invoiceStatus?: 'Pending' | 'Invoiced'; // New: Track if fapiao has been issued for this payment
  remarks?: string;
}

export interface MonthlyTrend {
  month: string;
  occupancyRate: number;
  revenueTarget: number;
  revenueCollected: number | null; // Changed to allow null for future months
  avgUnitPrice: number; // Average Rent Unit Price (Daily)
  collectionRate: number | null; // Changed to allow null for future months
}

export interface BillingDetail {
  tenantId: string;
  tenantName: string;
  unitIds: string[];
  amountDue: number;
  amountPaid: number;
  status: 'Paid' | 'Unpaid' | 'Partial' | 'Overdue';
  deferredToPeriod?: string;
  deferredFromPeriod?: string;
  deferredAmount?: number;
  /** 自其他账期缓缴调入的金额合计（目标账期行展示） */
  deferredInAmount?: number;
  /** 调入来源账期标签，如 "2026-03" 或多条用顿号连接 */
  deferredInFromSummary?: string;
}

export interface ParkingStatDetail {
  tenantId: string;
  tenantName: string;
  contractCount: number;
  actualCount: number;
  // Revenue details removed as requested
}

export interface BudgetAssumption {
  id: string;
  targetType: 'Vacancy' | 'Renewal' | 'RiskTermination' | 'Existing'; 
  targetId: string; // Unit ID or Tenant ID
  targetName: string; // Unit Name or Tenant Name
  
  // Strategy for Expiring/Risk Tenants
  strategy?: 'Renewal' | 'ReLease'; // Renewal=Continue, ReLease=Terminate & Find New
  
  // For Risk Tenants
  projectedTerminationDate?: string; // When do we expect them to leave?

  // For Re-lease / Vacancy / Risk Replacement
  vacancyGapMonths?: number; // Months empty before new tenant
  projectedSignDate: string; // Estimated start date (auto-calc based on gap usually)
  projectedUnitPrice: number; // Estimated Daily Price
  projectedRentFreeMonths: number; // Estimated rent free months

  // For Existing Contracts (Settings)
  billingCycleShiftMonths?: number; // Positive = Delay, Negative = Advance

  priceAdjustment?: {
      startDate: string;
      endDate: string;
      newUnitPrice: number;
  };
  paymentShift?: {
      amount: number;
      fromYear: number;
      fromMonth: number; // 0-11
      toYear: number;
      toMonth: number;   // 0-11
      isActive: boolean;
  };
}

export interface BudgetAdjustment {
  id: string;
  tenantId: string;
  tenantName: string;
  originalYear: number;
  originalMonth: number; // 0-11
  adjustedYear: number;
  adjustedMonth: number; // 0-11
  amount: number;
  reason: string; // e.g., "Pre-payment for next year", "Deferred payment"
  /** period_shift: 账期调整；amount_delta: 仅金额增减（此时 original 常为 -1，由 billingService 只做加项） */
  adjustmentKind?: 'period_shift' | 'amount_delta';
}

export interface BudgetAnalysisData {
    occupancy: string;
    revenue: string;
    execution?: string; // New field for Budget vs Actual analysis
}

export interface CloudConfig {
    /** 仅使用 PocketBase 作为持久化后端 */
    provider: 'pocketbase';
    autoSync: boolean;
    projectId: string; // Identifier for this park's data
    pocketbaseUrl?: string;
    pocketbaseEmail?: string;
    pocketbasePassword?: string;
}

export interface AIConfig {
    provider: 'qwen' | 'openai' | 'none';
    qwenApiKey?: string;
    qwenBaseUrl?: string; // 千问 OpenAI 兼容协议 Base URL
    openaiApiKey?: string;
    openaiBaseUrl?: string;
    enabled: boolean;
}

export interface CloudBackupMetadata {
    id: string;
    created_at: string;
    note?: string;
}

export interface BudgetScenario {
    id: string;
    name: string;
    /** 方案归属预算年度（例如 2026 / 2027） */
    budgetYear: number;
    description?: string;
    createdAt: string;
    isActive: boolean; // Active within its budgetYear
    /** 应收款专用方案（每年最多一个），用于工作台/财务应收口径 */
    isReceivableActive?: boolean;
    
    // The Rules
    assumptions: BudgetAssumption[];
    adjustments: BudgetAdjustment[];
    
    // The Snapshot (Business state at the time of creation)
    // Optional: if not present, uses current live data
    baseDataSnapshot?: {
        tenants: Tenant[];
        buildings: Building[];
    };
}

export interface TenantSearchResult {
    moments: KeyMoment[];
    foundingDate?: string;
    industry?: string;
}

export interface MonthlyInitData {
    year: number;
    month: number; // 1-12
    revenueTarget: number;
    revenueCollected: number;
    occupancyRate: number;
    accumulatedArrears?: number; // 新增：初始化累计欠款（2025年及之前的欠款）
}

// New: Invoice Management
export interface InvoiceRecord {
    id: string;
    tenantId: string;
    billDate: string; // Original Due Date (from Budget)
    targetInvoiceDate: string; // User adjusted or Default (billDate - 1 month)
    amount: number;
    status: 'Pending' | 'Invoiced';
    invoicedAt?: string; // Timestamp when clicked
    deferReason?: string;
}

export interface DashboardData {
  buildings: Building[];
  tenants: Tenant[];
  payments: PaymentRecord[];
  
  // Computed metrics (Current Selected Year)
  totalArea: number;
  leasedArea: number;
  occupancyRate: number;
  
  // Financials (Current Selected Year)
  annualRevenueTarget: number;
  annualRevenueCollected: number;
  annualOccupancyTarget: number;
  
  monthlyRevenueTarget: number;
  monthlyRevenueCollected: number;
  collectionRate: number; // 保留以便其他地方使用
  accumulatedArrears: number; // 新增：累计欠款（截止当期，应交未交的租金）

  newContractsCount: number;
  newContractsArea: number; 
  terminatedContractsCount: number; // New
  terminatedContractsArea: number; // New
  netIncreaseArea: number; // New
  expiringSoonCount: number;

  // New: Yearly Targets Map
  // Key: Year (e.g., 2024), Value: Targets
  yearlyTargets?: Record<number, { revenue: number, occupancy: number }>;

  // Visual/List data
  recentSignings: Tenant[];
  expiringSoon: Tenant[];
  monthlyTrends: MonthlyTrend[];
  prevYearMonthlyTrends?: MonthlyTrend[]; // New: YoY Analysis
  currentMonthBilling: BillingDetail[];

  // New: Parking Stats
  parkingStats: {
      totalContractSpaces: number;
      totalActualSpaces: number;
      totalMonthlyRevenue: number; // Based on Actual
      details: ParkingStatDetail[];
  };

  // New: Budget Management
  budgetAssumptions: BudgetAssumption[];
  budgetAdjustments: BudgetAdjustment[];
  budgetAnalysis: BudgetAnalysisData;
  budgetScenarios?: BudgetScenario[]; // New: Multiple scenarios
  
  // New: Initialization Data
  initializationData?: MonthlyInitData[];

  // New: Invoice Records
  invoices?: InvoiceRecord[];

  /** 缓缴等仅影响应收展示，不写入 budgetAdjustments */
  billingPeriodNotes?: Record<string, string>;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}
