
export enum ContractStatus {
  Active = 'Active',       // 履约中
  Expiring = 'Expiring',   // 即将到期
  Terminated = 'Terminated', // 已退租
  Pending = 'Pending',     // 签约中
  Expired = 'Expired',     // 已到期(历史合同)
}

export enum UnitStatus {
  Vacant = 'Vacant',       // 空置
  Occupied = 'Occupied',   // 已租
  Reserved = 'Reserved',   // 预留
}

export enum DepositStatus {
  Unpaid = 'Unpaid',
  Paid = 'Paid',
  Refunded = 'Refunded',
  Deducted = 'Deducted', // 抵扣
}

export type PaymentCycle = 'HalfMonthly' | 'Monthly' | 'BiMonthly' | 'Quarterly' | 'SemiAnnual' | 'Annual' | 'Custom';

export interface RentFreePeriod {
  start: string;
  end: string;
  description: string;
}

export interface LeaseUnitTerm {
  unitId: string;
  unitName?: string;
  area: number;
  unitPrice?: number;
  monthlyRent?: number;
  rentFreePeriods?: RentFreePeriod[];
}

export interface Unit {
  id: string;
  name: string; // e.g., 101, 102
  area: number;
  status: UnitStatus;
  floor: number;
  isSelfUse?: boolean;
}

export interface Building {
  id: string;
  name: string; // e.g., 1号楼
  type?: 'Building' | 'Site'; // 新增：区分楼宇或场地 (默认为 Building)
  units: Unit[];
}

export interface KeyMoment {
  id: string;
  date: string; // YYYY-MM-DD or YYYY-MM
  title: string;
  description: string;
  type: 'Anniversary' | 'Product' | 'News' | 'Award' | 'Other' | 'ParkAnniversary';
  sourceUrl?: string;
  isAutoGenerated?: boolean;
}

export interface NameChangeRecord {
  id: string;
  oldName: string;
  newName: string;
  changedAt: string; // ISO date
  reason?: string;
  operatorName?: string;
}

export interface PaymentCycleChange {
  id: string;
  fromCycle: PaymentCycle;
  toCycle: PaymentCycle;
  fromCycleMonths?: number;
  toCycleMonths?: number;
  effectiveDate: string; // YYYY-MM-DD
  reason?: string;
  operatorName?: string;
  createdAt: string; // ISO timestamp
}

export interface Tenant {
  id: string;
  rootId?: string; // 根ID，用于关联同一个客户的历史续签记录
  name: string;
  contactInfo?: string;
  industry?: string;
  
  // Basic Info for Insights
  foundingDate?: string; // YYYY-MM-DD
  legalRepName?: string; // 法人/管理层姓名
  legalRepBirthday?: string; // MM-DD or YYYY-MM-DD
  contactName?: string; // 对接人姓名
  contactBirthday?: string; // MM-DD or YYYY-MM-DD

  // Link to Asset
  buildingId: string;
  unitIds: string[]; 
  totalArea: number;

  // Lease Terms
  signingDate?: string; // 新增：合同签约时间
  leaseStart: string;
  leaseEnd: string;
  /** 实际入驻日期（用于入园周年等关键时刻；未填时回退为起租日） */
  moveInDate?: string;

  // Rent
  unitPrice?: number; // Price per sqm per DAY
  monthlyRent: number; // Total monthly rent (calculated)

  unitTerms?: LeaseUnitTerm[];
  paymentTerms?: LeaseUnitTerm[];
  rentFreePeriods: RentFreePeriod[];

  // Payment Terms
  paymentCycle: PaymentCycle;
  paymentCycleMonths?: number; // Flexible months input (e.g. 0.5, 1, 2, 3, 6, 12)
  firstPaymentDate: string;
  firstPaymentMonths?: number;
  /** 首期应收自定义金额（元），与计费引擎首期账单对齐时可覆盖首笔金额 */
  firstReceivableAmount?: number;
  /** 首期覆盖开始（YYYY-MM-DD），可选 */
  firstReceivableStartDate?: string;
  /** 首期覆盖结束（YYYY-MM-DD），可选 */
  firstReceivableEndDate?: string;
  
  // New: Billing Strategy (免租期处理方式)
  // 'Deduct': 当期账单扣除 - 在当期账单中扣除免租期月数，收款时间不变但金额减少
  // 'Defer': 账期顺延 - 免租期月份不产生账单，收款时间整体顺延
  freeRentHandling?: 'Deduct' | 'Defer';

  // Deposit
  depositAmount: number;
  depositStatus: DepositStatus;

  // Termination
  status: ContractStatus;
  terminationDate?: string;
  terminationType?: 'Normal' | 'Early';
  terminationReason?: string;
  /** 提前退租：免租扣回金额手工覆盖（元）；不填则按「已享免租 − 比例应享」×月租金公式计算 */
  earlyTerminationFreeRentClawbackOverride?: number;
  /** 提前退租：押金扣款（元，可自定义，计入最后一期应收） */
  earlyTerminationDepositDeduction?: number;
  /** 提前退租：其它结算调整（元，正数为加收、负数为减免，计入最后一期应收） */
  earlyTerminationOtherAdjustment?: number;
  
  // 合同级账期调整（在合同管理中操作，所有预算方案自动引用）
  paymentPeriodAdjustments?: PaymentPeriodAdjustment[];
  /** 整体账期偏移：正数=后移N个月，负数=前移N个月（例如 -1 = 所有收款日期提前1个月） */
  paymentPeriodShiftMonths?: number;

  // Special requirements
  specialRequirements?: string;
  
  // Risk Management
  isRisk?: boolean; // High risk flag

  /**
   * 特殊业态：租户不按固定租金计算（如经营分成、按实结算等），系统不再按合同自动产生应收。
   * 应收金额需要在「财务报表 → 特殊业态收入录入」中按月手动录入，
   * 录入后的金额会推送到当月「应收核销」列表参与开票/收款流程。
   */
  isSpecialBusiness?: boolean;

  // New: Parking
  // parkingSpaces field is deprecated in favor of specific fields below, but kept for legacy type safety if needed
  parkingSpaces?: number; 
  
  contractParkingSpaces?: number; // Contracted/Agreed number of spaces
  actualParkingSpaces?: number;   // Actually activated/paid spaces

  parkingUnitPrice?: number; // Price per space per month

  // New: Customer Insights
  keyMoments?: KeyMoment[];

  // Name change history
  nameHistory?: NameChangeRecord[];

  // Payment cycle changes mid-contract
  paymentCycleChanges?: PaymentCycleChange[];
}

export interface PaymentRecord {
  id: string;
  tenantId: string;
  tenantName: string;
  amount: number;
  type: 'Rent' | 'Deposit' | 'ManagementFee' | 'ParkingFee' | 'Other' | 'DepositToRent' | 'DepositRefund'; // Added ParkingFee
  date: string;
  /** 关联账期，支持单个或多个 YYYY-MM（逗号分隔），用于提前收款核销未来应收 */
  period?: string;
  status: 'Received' | 'Pending';
  invoiceStatus?: 'Pending' | 'Invoiced'; // New: Track if fapiao has been issued for this payment
  remarks?: string;
}

export interface MonthlyTrend {
  month: string;
  occupancyRate: number;
  revenueTarget: number;
  /** 合同应收 = 当前所有履约合同按条款滚动计算的应收（不受初始化数据覆盖） */
  contractReceivable?: number;
  revenueCollected: number | null; // Changed to allow null for future months
  avgUnitPrice: number; // Average Rent Unit Price (Daily)
  collectionRate: number | null; // Changed to allow null for future months
}

export interface BillingDetail {
  tenantId: string;
  tenantName: string;
  unitIds: string[];
  amountDue: number;
  amountPaid: number;
  status: 'Paid' | 'Unpaid' | 'Partial' | 'Overdue';
  deferredToPeriod?: string;
  deferredFromPeriod?: string;
  deferredAmount?: number;
  /** 自其他账期缓缴调入的金额合计（目标账期行展示） */
  deferredInAmount?: number;
  /** 调入来源账期标签，如 "2026-03" 或多条用顿号连接 */
  deferredInFromSummary?: string;
  /** 提前退租最后一期：免租扣回/押金等明细（金额已含在 amountDue 中） */
  earlyTerminationBreakdown?: string;
  /** 与「预算管理 → 空置去化」卡片对齐时的说明（合同起租一致则推算口径已对齐） */
  budgetAlignmentNote?: string;
  /** 当月推算应收实际采用的租户条款（应收专用方案快照与实时合同合并后）；合同概要弹窗应对齐此对象而非仅根 tenants */
  billingTermsTenant?: Tenant;
}

export interface ParkingStatDetail {
  tenantId: string;
  tenantName: string;
  contractCount: number;
  actualCount: number;
  // Revenue details removed as requested
}

export interface BudgetAssumption {
  id: string;
  targetType: 'Vacancy' | 'Renewal' | 'RiskTermination' | 'Existing'; 
  targetId: string; // Unit ID or Tenant ID
  targetName: string; // Unit Name or Tenant Name
  
  // Strategy for Expiring/Risk Tenants
  strategy?: 'Renewal' | 'ReLease'; // Renewal=Continue, ReLease=Terminate & Find New
  
  // For Risk Tenants
  projectedTerminationDate?: string; // When do we expect them to leave?

  // For Re-lease / Vacancy / Risk Replacement
  vacancyGapMonths?: number; // Months empty before new tenant
  projectedSignDate: string; // Estimated start date (auto-calc based on gap usually)
  projectedUnitPrice: number; // Estimated Daily Price
  projectedRentFreeMonths: number; // Estimated rent free months

  // For Existing Contracts (Settings)
  billingCycleShiftMonths?: number; // Positive = Delay, Negative = Advance

  priceAdjustment?: {
      startDate: string;
      endDate: string;
      newUnitPrice: number;
  };
  paymentShift?: {
      amount: number;
      fromYear: number;
      fromMonth: number; // 0-11
      toYear: number;
      toMonth: number;   // 0-11
      isActive: boolean;
  };
}

/** 合同级账期调整：从原账期月份移动金额到目标月份，存储在 Tenant 上，所有预算方案自动引用 */
export interface PaymentPeriodAdjustment {
  id: string;
  /** 原账期年份（与合同 leaseStart 同年偏移） */
  originalYear: number;
  /** 原账期月份 (0-11) */
  originalMonth: number;
  /** 目标年份 */
  adjustedYear: number;
  /** 目标月份 (0-11) */
  adjustedMonth: number;
  /** 移动金额 */
  amount: number;
  /** 调整原因 */
  reason: string;
}

export interface BudgetAdjustment {
  id: string;
  tenantId: string;
  tenantName: string;
  originalYear: number;
  originalMonth: number; // 0-11
  adjustedYear: number;
  adjustedMonth: number; // 0-11
  amount: number;
  reason: string; // e.g., "Pre-payment for next year", "Deferred payment"
  /** period_shift: 账期调整；amount_delta: 仅金额增减（此时 original 常为 -1，由 billingService 只做加项） */
  adjustmentKind?: 'period_shift' | 'amount_delta';
}

export interface BudgetAnalysisData {
    occupancy: string;
    revenue: string;
    execution?: string; // New field for Budget vs Actual analysis
}

export interface CloudConfig {
    /** 仅使用 PocketBase 作为持久化后端 */
    provider: 'pocketbase';
    autoSync: boolean;
    projectId: string; // Identifier for this park's data
    pocketbaseUrl?: string;
    pocketbaseEmail?: string;
    pocketbasePassword?: string;
}

export type UserRole = 'park_user' | 'park_admin' | 'group_admin' | 'platform_admin';

export interface ParkInfo {
    id?: string;
    projectId: string;
    name: string;
    city?: string;
    enabled: boolean;
    sortOrder?: number;
}

export interface AuthUser {
    id: string;
    email: string;
    name?: string;
    projectId: string;
    role: UserRole;
    allowedProjectIds: string[];
    enabled: boolean;
}

export interface AIConfig {
    provider: 'qwen' | 'openai' | 'none';
    qwenApiKey?: string;
    qwenBaseUrl?: string; // 千问 OpenAI 兼容协议 Base URL
    openaiApiKey?: string;
    openaiBaseUrl?: string;
    enabled: boolean;
}

export interface CloudBackupMetadata {
    id: string;
    created_at: string;
    note?: string;
}

export interface BudgetScenario {
    id: string;
    name: string;
    /** 方案归属预算年度（例如 2026 / 2027） */
    budgetYear: number;
    description?: string;
    createdAt: string;
    isActive: boolean; // Active within its budgetYear
    /** 应收款专用方案（每年最多一个），用于工作台/财务应收口径 */
    isReceivableActive?: boolean;
    
    // The Rules
    assumptions: BudgetAssumption[];
    adjustments: BudgetAdjustment[];
    
    // The Snapshot (Business state at the time of creation)
    // Optional: if not present, uses current live data
    baseDataSnapshot?: {
        tenants: Tenant[];
        buildings: Building[];
    };
}

export interface TenantSearchResult {
    moments: KeyMoment[];
    foundingDate?: string;
    industry?: string;
}

export interface MonthlyInitData {
    year: number;
    month: number; // 1-12
    revenueTarget: number;
    revenueCollected: number;
    occupancyRate: number;
    accumulatedArrears?: number; // 新增：初始化累计欠款（2025年及之前的欠款）
    initialBudget?: number; // 月度年初预算（从生效预算方案导入或手填）
}

// New: Invoice Management
export interface InvoiceRecord {
  id: string;
  tenantId: string;
  billDate: string; // Original Due Date (from Budget)
  targetInvoiceDate: string; // User adjusted or Default (billDate - 1 month)
  amount: number;
  status: 'Pending' | 'Invoiced';
  invoicedAt?: string; // Timestamp when clicked
  deferReason?: string;
}

/** 手工应收行（存于 billingPeriodNotes 的 JSON，tenantId 为空时表示不关联系统客户） */
export interface ManualReceivableLine {
  id: string;
  tenantId?: string;
  /** 不关联客户时的展示名 / 与「应收项目」同步 */
  customerLabel: string;
  /** 应收项目名称 */
  title?: string;
  amount: number;
  /** 归属账期 YYYY-MM */
  periodYYYYMM: string;
}

/**
 * 特殊业态月度应收（按租户 + 账期录入）：
 * - 同一 tenantId + periodYYYYMM 唯一；后录入的会覆盖之前录入的金额；
 * - 录入即视作当月该客户的应收，会推送到「应收核销」列表参与开票/收款；
 * - 不再依赖合同自动滚动账单。
 */
export interface SpecialBusinessReceivable {
  id: string;
  tenantId: string;
  /** 归属账期 YYYY-MM */
  periodYYYYMM: string;
  amount: number;
  /** 业态分成依据 / 经营备注 */
  remark?: string;
  /** 录入时间，方便排序与审计 */
  updatedAt?: string;
}

export interface DashboardData {
  buildings: Building[];
  tenants: Tenant[];
  payments: PaymentRecord[];
  
  // Computed metrics (Current Selected Year)
  totalArea: number;
  leasedArea: number;
  occupancyRate: number;
  
  // Financials (Current Selected Year)
  annualRevenueTarget: number;
  annualRevenueCollected: number;
  annualOccupancyTarget: number;
  
  monthlyRevenueTarget: number;
  monthlyRevenueCollected: number;
  collectionRate: number; // 保留以便其他地方使用
  accumulatedArrears: number; // 新增：累计欠款（截止当期，应交未交的租金）

  newContractsCount: number;
  newContractsArea: number; 
  terminatedContractsCount: number; // New
  terminatedContractsArea: number; // New
  netIncreaseArea: number; // New
  expiringSoonCount: number;

  // New: Yearly Targets Map
  // Key: Year (e.g., 2024), Value: Targets
  yearlyTargets?: Record<number, { revenue: number, occupancy: number; initialBudget?: number }>;

  // Visual/List data
  recentSignings: Tenant[];
  expiringSoon: Tenant[];
  monthlyTrends: MonthlyTrend[];
  prevYearMonthlyTrends?: MonthlyTrend[]; // New: YoY Analysis
  currentMonthBilling: BillingDetail[];

  // New: Parking Stats
  parkingStats: {
      totalContractSpaces: number;
      totalActualSpaces: number;
      totalMonthlyRevenue: number; // Based on Actual
      details: ParkingStatDetail[];
  };

  // New: Budget Management
  budgetAssumptions: BudgetAssumption[];
  budgetAdjustments: BudgetAdjustment[];
  budgetAnalysis: BudgetAnalysisData;
  budgetScenarios?: BudgetScenario[]; // New: Multiple scenarios
  
  // New: Initialization Data
  initializationData?: MonthlyInitData[];

  // New: Invoice Records
  invoices?: InvoiceRecord[];

  /** 缓缴等仅影响应收展示，不写入 budgetAdjustments（手工应收 JSON 亦存于此，键见 receivableListHelpers） */
  billingPeriodNotes?: Record<string, string>;

  /**
   * 与 PocketBase 中 `dashboard_data_version` 记录对齐；保存时必须与服务器一致，否则触发冲突提示。
   * 未从云端加载过时可视为 0。
   */
  cloudSaveVersion?: number;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}
