import React, { useState } from 'react';
import { Tenant, KeyMoment } from '../types';
import { searchTenantInsights } from '../services/geminiService';
import { Sparkles, Calendar, ExternalLink, Search, Globe, Award, Megaphone, Clock, Building2, Loader2, RefreshCw, Briefcase, User, Phone, Cake, ArrowLeft, Flag, Edit2, Repeat } from 'lucide-react';
import { paymentCycleLabelMap } from '../services/sharedUtils';

interface TenantInsightsProps {
  tenants: Tenant[];
  onUpdateTenants: (tenants: Tenant[]) => void;
}

export const TenantInsights: React.FC<TenantInsightsProps> = ({ tenants, onUpdateTenants }) => {
  const [selectedTenantId, setSelectedTenantId] = useState<string>(tenants[0]?.id || '');
  const [isSearching, setIsSearching] = useState(false);
  const [batchProgress, setBatchProgress] = useState<{current: number, total: number} | null>(null);
  const [searchFilter, setSearchFilter] = useState('');
  
  // Mobile view state: true = list view, false = detail view
  const [showMobileList, setShowMobileList] = useState(true);

  const selectedTenant = tenants.find(t => t.id === selectedTenantId);
  const filteredTenants = tenants.filter(t => t.name.toLowerCase().includes(searchFilter.toLowerCase()));

  const handleTenantSelect = (id: string) => {
      setSelectedTenantId(id);
      setShowMobileList(false); // Switch to detail view on mobile
  };

  const handleBatchCollect = async () => {
      if (filteredTenants.length === 0) return;
      
      setIsSearching(true);
      setBatchProgress({ current: 0, total: filteredTenants.length });
      
      let updatedTenantsList = [...tenants];
      let processedCount = 0;

      // Process sequentially to avoid rate limits
      for (const tenant of filteredTenants) {
          try {
              const result = await searchTenantInsights(tenant.name);
              
              const tenantIndex = updatedTenantsList.findIndex(t => t.id === tenant.id);
              if (tenantIndex !== -1) {
                  const t = updatedTenantsList[tenantIndex];
                  // Auto-fill Industry if found and not already set (or overwrite if empty)
                  const newIndustry = result.industry && (!t.industry || t.industry === '未录入') ? result.industry : t.industry;
                  
                  updatedTenantsList[tenantIndex] = {
                      ...t,
                      keyMoments: result.moments,
                      foundingDate: t.foundingDate || result.foundingDate || t.foundingDate,
                      industry: newIndustry
                  };
              }
          } catch (e) {
              console.error(`Failed to collect for ${tenant.name}`, e);
          }
          processedCount++;
          setBatchProgress({ current: processedCount, total: filteredTenants.length });
      }

      onUpdateTenants(updatedTenantsList);
      setIsSearching(false);
      setBatchProgress(null);
  };

  const getIconForType = (type: KeyMoment['type'] | 'ParkAnniversary') => {
    switch (type) {
      case 'Anniversary': return <Calendar className="text-rose-500" size={18} />;
      case 'Product': return <Megaphone className="text-blue-500" size={18} />;
      case 'Award': return <Award className="text-amber-500" size={18} />;
      case 'News': return <Globe className="text-indigo-500" size={18} />;
      case 'ParkAnniversary': return <Flag className="text-emerald-500" size={18} />;
      default: return <Clock className="text-slate-400" size={18} />;
    }
  };

  const getTypeLabel = (type: KeyMoment['type'] | 'ParkAnniversary') => {
      const map: Record<string, string> = {
          'Anniversary': '司庆/成立',
          'Product': '产品发布',
          'Award': '荣誉奖项',
          'News': '重大新闻',
          'ParkAnniversary': '入园纪念',
          'Other': '其他动态'
      };
      return map[type] || type;
  };

  // Helper: Calculate Duration in Park
  const calculateParkDuration = (startDate: string) => {
      if (!startDate) return '未开始';
      const start = new Date(startDate);
      const now = new Date();
      const diffTime = Math.abs(now.getTime() - start.getTime());
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
      
      const years = Math.floor(diffDays / 365);
      const days = diffDays % 365;
      
      if (years > 0) return `${years}年 ${days}天`;
      return `${days}天`;
  };

  const parkDurationForTenant = (t: Tenant) => {
      const ref = t.moveInDate || t.leaseStart;
      return ref ? calculateParkDuration(ref) : '未入驻';
  };

  // Helper: Generate Park Anniversary Moments dynamically based on 实际入驻日（缺省为起租日）
  const generateParkMoments = (tenant: Tenant): (KeyMoment & { isAutoGenerated?: boolean })[] => {
      const parkRef = tenant.moveInDate || tenant.leaseStart;
      if (!parkRef) return [];
      
      const moments: (KeyMoment & { isAutoGenerated?: boolean })[] = [];
      const start = new Date(parkRef);
      const now = new Date();
      const currentYear = now.getFullYear();
      const startYear = start.getFullYear();

      // Start Date Moment
      moments.push({
          id: `park_start_${tenant.id}`,
          date: parkRef,
          title: tenant.moveInDate ? '实际入驻园区' : '正式入驻园区',
          description: `签约入驻 ${tenant.unitIds.length} 个单元，开启合作旅程。`,
          type: 'ParkAnniversary', // Custom mapped type
          isAutoGenerated: true
      } as any);

      // Yearly Anniversaries
      for (let year = startYear + 1; year <= currentYear + 1; year++) {
          const anniversaryDate = new Date(start);
          anniversaryDate.setFullYear(year);
          const dateStr = anniversaryDate.toISOString().split('T')[0];
          
          // Only show up to current time + 1 year forecast
          // Calculate which anniversary it is
          const nth = year - startYear;
          
          if (nth > 0) {
              moments.push({
                  id: `park_anniversary_${tenant.id}_${year}`,
                  date: dateStr,
                  title: `入园 ${nth} 周年纪念`,
                  description: `感谢陪伴！${tenant.name} 加入园区已满 ${nth} 周年。`,
                  type: 'ParkAnniversary',
                  isAutoGenerated: true
              } as any);
          }
      }
      return moments;
  };

  // Combine stored moments with generated park moments
  const allMoments = selectedTenant 
      ? [...(selectedTenant.keyMoments || []), ...generateParkMoments(selectedTenant)].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime())
      : [];

  return (
    <div className="flex min-h-[320px] h-[calc(100dvh-10rem)] md:h-[calc(100vh-140px)] bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden min-w-0">
        {/* Left Sidebar: Tenant List */}
        <div className={`w-full md:w-80 border-r border-slate-200 flex flex-col bg-slate-50 min-w-0 ${showMobileList ? 'flex' : 'hidden md:flex'}`}>
            <div className="p-4 border-b border-slate-200 space-y-3">
                <h3 className="font-bold text-slate-700 flex items-center gap-2">
                    <Sparkles size={18} className="text-purple-500"/> 客户洞察
                </h3>
                <div className="relative">
                    <Search className="absolute left-3 top-2.5 text-slate-400 w-4 h-4" />
                    <input 
                        type="text" 
                        placeholder="搜索客户..." 
                        className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-purple-100"
                        value={searchFilter}
                        onChange={e => setSearchFilter(e.target.value)}
                    />
                </div>
                <button 
                    onClick={handleBatchCollect}
                    disabled={isSearching}
                    className="w-full bg-white border border-purple-200 text-purple-600 py-2 rounded-lg text-xs font-medium hover:bg-purple-50 flex items-center justify-center gap-2 transition-colors disabled:opacity-50"
                >
                    {isSearching ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
                    {isSearching ? `正在更新... (${batchProgress?.current}/${batchProgress?.total})` : '一键更新全员动态'}
                </button>
            </div>
            <div className="flex-1 overflow-y-auto">
                {filteredTenants.map(t => (
                    <div 
                        key={t.id}
                        onClick={() => handleTenantSelect(t.id)}
                        className={`p-4 border-b border-slate-100 cursor-pointer hover:bg-white transition-colors ${selectedTenantId === t.id ? 'bg-white border-l-4 border-l-purple-500 shadow-sm' : 'border-l-4 border-l-transparent'}`}
                    >
                        <div className="font-medium text-slate-800 text-sm">{t.name}</div>
                        <div className="text-xs text-slate-500 mt-1 flex items-center gap-2">
                            <span>{t.industry || '行业未录入'}</span>
                            <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
                            <span>{parkDurationForTenant(t)}</span>
                        </div>
                    </div>
                ))}
                {filteredTenants.length === 0 && (
                    <div className="p-8 text-center text-slate-400 text-xs">未找到匹配客户</div>
                )}
            </div>
        </div>

        {/* Right Main: Details */}
        <div className={`flex-1 flex-col min-w-0 ${!showMobileList ? 'flex' : 'hidden md:flex'}`}>
            {selectedTenant ? (
                <>
                    {/* Header */}
                    <div className="p-6 border-b border-slate-200 bg-white">
                        <div className="md:hidden mb-4">
                             <button onClick={() => setShowMobileList(true)} className="text-slate-500 flex items-center gap-1 text-sm"><ArrowLeft size={16}/> 返回列表</button>
                        </div>
                        <div className="flex justify-between items-start">
                            <div>
                                <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
                                    {selectedTenant.name}
                                    {selectedTenant.industry && <span className="bg-purple-100 text-purple-700 text-xs px-2 py-1 rounded-full font-medium">{selectedTenant.industry}</span>}
                                </h2>
                                <div className="flex flex-wrap items-center gap-4 mt-3 text-sm text-slate-500">
                                    <div className="flex items-center gap-1.5" title="成立日期">
                                        <Cake size={16} className="text-pink-400"/>
                                        <span>成立: {selectedTenant.foundingDate || '未知'}</span>
                                    </div>
                                    <div className="flex items-center gap-1.5" title="入驻时长">
                                        <Building2 size={16} className="text-blue-400"/>
                                        <span>入驻: {calculateParkDuration(selectedTenant.moveInDate || selectedTenant.leaseStart)}</span>
                                    </div>
                                    <div className="flex items-center gap-1.5" title="法人代表">
                                        <User size={16} className="text-slate-400"/>
                                        <span>法人: {selectedTenant.legalRepName || '未知'}</span>
                                    </div>
                                </div>
                            </div>
                            <button className="text-sm text-purple-600 hover:text-purple-800 flex items-center gap-1 px-3 py-1.5 bg-purple-50 rounded-lg hover:bg-purple-100 transition-colors"
                                onClick={() => {
                                    // Trigger single update
                                    const dummyList = [selectedTenant]; // Hack to reuse logic or just implement single update
                                    alert("单个客户更新功能开发中，请使用左侧批量更新");
                                }}
                            >
                                <RefreshCw size={14}/> 更新动态
                            </button>
                        </div>
                    </div>

                    {/* Timeline Content */}
                    <div className="flex-1 overflow-y-auto p-6 bg-slate-50/50 space-y-6">
                         {/* 时间轴 */}
                         {allMoments.length > 0 ? (
                             <div className="relative border-l-2 border-slate-200 ml-4 space-y-8 pb-8">
                                 {allMoments.map((moment, index) => (
                                     <div key={moment.id || index} className="relative pl-8 group">
                                         <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-white border-2 border-slate-300 group-hover:border-purple-500 transition-colors"></div>
                                         <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-all group-hover:border-purple-200">
                                             <div className="flex justify-between items-start mb-2">
                                                 <div className="flex items-center gap-2">
                                                     {getIconForType(moment.type as any)}
                                                     <span className="text-xs font-bold uppercase tracking-wider text-slate-500">{getTypeLabel(moment.type as any)}</span>
                                                     {moment.isAutoGenerated && <span className="bg-slate-100 text-slate-400 text-[10px] px-1.5 py-0.5 rounded">系统生成</span>}
                                                 </div>
                                                 <span className="text-sm font-medium text-slate-400">{moment.date}</span>
                                             </div>
                                             <h4 className="text-lg font-bold text-slate-800 mb-1">{moment.title}</h4>
                                             <p className="text-slate-600 text-sm leading-relaxed">{moment.description}</p>
                                             {moment.sourceUrl && (
                                                 <a href={moment.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-blue-500 hover:underline mt-3">
                                                     查看来源 <ExternalLink size={10} />
                                                 </a>
                                             )}
                                         </div>
                                     </div>
                                 ))}
                             </div>
                         ) : (
                             <div className="flex flex-col items-center justify-center h-full text-slate-400">
                                 <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                                     <Sparkles size={24} className="opacity-50"/>
                                 </div>
                                 <p>暂无动态记录</p>
                                 <p className="text-xs mt-1">点击左侧"更新全员动态"获取AI洞察</p>
                             </div>
                         )}

                         {/* 名称变更记录 */}
                         {(selectedTenant.nameHistory && selectedTenant.nameHistory.length > 0) && (
                             <div>
                                 <h3 className="flex items-center gap-2 text-sm font-bold text-slate-600 mb-3"><Edit2 size={16} className="text-amber-500"/> 名称变更记录</h3>
                                 <div className="relative border-l-2 border-amber-200 ml-4 space-y-4">
                                     {[...selectedTenant.nameHistory].reverse().map(r => (
                                         <div key={r.id} className="relative pl-8">
                                             <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-white border-2 border-amber-300"></div>
                                             <div className="bg-white p-3 rounded-lg border border-slate-200 text-sm">
                                                 <div className="flex items-center gap-2 text-slate-500">
                                                     <span className="line-through text-slate-400">{r.oldName}</span>
                                                     <span className="text-slate-300">→</span>
                                                     <span className="font-medium text-slate-700">{r.newName}</span>
                                                 </div>
                                                 <div className="flex items-center gap-2 mt-1 text-xs text-slate-400">
                                                     <span>{r.changedAt?.slice(0, 10)}</span>
                                                     {r.reason && <span>· {r.reason}</span>}
                                                 </div>
                                             </div>
                                         </div>
                                     ))}
                                 </div>
                             </div>
                         )}

                         {/* 付款周期变更记录 */}
                         {(selectedTenant.paymentCycleChanges && selectedTenant.paymentCycleChanges.length > 0) && (
                             <div>
                                 <h3 className="flex items-center gap-2 text-sm font-bold text-slate-600 mb-3"><Repeat size={16} className="text-blue-500"/> 付款周期变更记录</h3>
                                 <div className="relative border-l-2 border-blue-200 ml-4 space-y-4">
                                     {[...selectedTenant.paymentCycleChanges].reverse().map(r => (
                                         <div key={r.id} className="relative pl-8">
                                             <div className="absolute -left-[9px] top-1 w-4 h-4 rounded-full bg-white border-2 border-blue-300"></div>
                                             <div className="bg-white p-3 rounded-lg border border-slate-200 text-sm">
                                                 <div className="flex items-center gap-2 text-slate-500">
                                                     <span className="text-slate-400">{paymentCycleLabelMap[r.fromCycle] || r.fromCycle}</span>
                                                     <span className="text-slate-300">→</span>
                                                     <span className="font-medium text-slate-700">{paymentCycleLabelMap[r.toCycle] || r.toCycle}</span>
                                                 </div>
                                                 <div className="flex items-center gap-2 mt-1 text-xs text-slate-400">
                                                     <span>生效: {r.effectiveDate}</span>
                                                     {r.reason && <span>· {r.reason}</span>}
                                                 </div>
                                             </div>
                                         </div>
                                     ))}
                                 </div>
                             </div>
                         )}
                    </div>
                </>
            ) : (
                <div className="flex flex-col items-center justify-center h-full text-slate-400 bg-slate-50/50">
                    <Building2 size={48} className="opacity-20 mb-4" />
                    <p>请选择一个客户查看详细洞察</p>
                </div>
            )}
        </div>
    </div>
  );
};