import React, { useState } from 'react';
import { Tenant, KeyMoment } from '../types';
import { searchTenantInsights } from '../services/geminiService';
import { Sparkles, Calendar, ExternalLink, Search, Globe, Award, Megaphone, Clock, Building2, Loader2, RefreshCw, Briefcase, User, Phone, Cake, ArrowLeft, Flag, Edit2, Repeat } from 'lucide-react';
import { paymentCycleLabelMap } from '../services/sharedUtils';

interface TenantInsightsProps {
  tenants: Tenant[];
  onUpdateTenants: (tenants: Tenant[]) => void;
}

export const TenantInsights: React.FC<TenantInsightsProps> = ({ tenants, onUpdateTenants }) => {
  const [selectedTenantId, setSelectedTenantId] = useState<string>(tenants[0]?.id || '');
  const [isSearching, setIsSearching] = useState(false);
  const [batchProgress, setBatchProgress] = useState<{current: number, total: number} | null>(null);
  const [searchFilter, setSearchFilter] = useState('');
  const [singleUpdateNotice, setSingleUpdateNotice] = useState(false);
  
  // Mobile view state: true = list view, false = detail view
  const [showMobileList, setShowMobileList] = useState(true);

  const selectedTenant = tenants.find(t => t.id === selectedTenantId);
  const filteredTenants = tenants.filter(t => t.name.toLowerCase().includes(searchFilter.toLowerCase()));

  const handleTenantSelect = (id: string) => {
      setSelectedTenantId(id);
      setSingleUpdateNotice(false);
      setShowMobileList(false); // Switch to detail view on mobile
  };

  const handleBatchCollect = async () => {
      if (filteredTenants.length === 0) return;
      
      setIsSearching(true);
      setBatchProgress({ current: 0, total: filteredTenants.length });
      
      let updatedTenantsList = [...tenants];
      let processedCount = 0;

      // Process sequentially to avoid rate limits
      for (const tenant of filteredTenants) {
          try {
              const result = await searchTenantInsights(tenant.name);
              
              const tenantIndex = updatedTenantsList.findIndex(t => t.id === tenant.id);
              if (tenantIndex !== -1) {
                  const t = updatedTenantsList[tenantIndex];
                  // Auto-fill Industry if found and not already set (or overwrite if empty)
                  const newIndustry = result.industry && (!t.industry || t.industry === '未录入') ? result.industry : t.industry;
                  
                  updatedTenantsList[tenantIndex] = {
                      ...t,
                      keyMoments: result.moments,
                      foundingDate: t.foundingDate || result.foundingDate || t.foundingDate,
                      industry: newIndustry
                  };
              }
          } catch (e) {
              console.error(`Failed to collect for ${tenant.name}`, e);
          }
          processedCount++;
          setBatchProgress({ current: processedCount, total: filteredTenants.length });
      }

      onUpdateTenants(updatedTenantsList);
      setIsSearching(false);
      setBatchProgress(null);
  };

  const getIconForType = (type: KeyMoment['type'] | 'ParkAnniversary') => {
    switch (type) {
      case 'Anniversary': return <Calendar className="text-rose-500" size={18} />;
      case 'Product': return <Megaphone className="text-blue-500" size={18} />;
      case 'Award': return <Award className="text-amber-500" size={18} />;
      case 'News': return <Globe className="text-blue-500" size={18} />;
      case 'ParkAnniversary': return <Flag className="text-blue-600" size={18} />;
      default: return <Clock className="text-slate-500" size={18} />;
    }
  };

  const getTypeLabel = (type: KeyMoment['type'] | 'ParkAnniversary') => {
      const map: Record<string, string> = {
          'Anniversary': '司庆/成立',
          'Product': '产品发布',
          'Award': '荣誉奖项',
          'News': '重大新闻',
          'ParkAnniversary': '入园纪念',
          'Other': '其他动态'
      };
      return map[type] || type;
  };

  // Helper: Calculate Duration in Park
  const calculateParkDuration = (startDate: string) => {
      if (!startDate) return '未开始';
      const start = new Date(startDate);
      const now = new Date();
      const diffTime = Math.abs(now.getTime() - start.getTime());
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
      
      const years = Math.floor(diffDays / 365);
      const days = diffDays % 365;
      
      if (years > 0) return `${years}年 ${days}天`;
      return `${days}天`;
  };

  const parkDurationForTenant = (t: Tenant) => {
      const ref = t.moveInDate || t.leaseStart;
      return ref ? calculateParkDuration(ref) : '未入驻';
  };

  // Helper: Generate Park Anniversary Moments dynamically based on 实际入驻日（缺省为起租日）
  const generateParkMoments = (tenant: Tenant): (KeyMoment & { isAutoGenerated?: boolean })[] => {
      const parkRef = tenant.moveInDate || tenant.leaseStart;
      if (!parkRef) return [];
      
      const moments: (KeyMoment & { isAutoGenerated?: boolean })[] = [];
      const start = new Date(parkRef);
      const now = new Date();
      const currentYear = now.getFullYear();
      const startYear = start.getFullYear();

      // Start Date Moment
      moments.push({
          id: `park_start_${tenant.id}`,
          date: parkRef,
          title: tenant.moveInDate ? '实际入驻园区' : '正式入驻园区',
          description: `签约入驻 ${tenant.unitIds.length} 个单元，开启合作旅程。`,
          type: 'ParkAnniversary', // Custom mapped type
          isAutoGenerated: true
      } as any);

      // Yearly Anniversaries
      for (let year = startYear + 1; year <= currentYear + 1; year++) {
          const anniversaryDate = new Date(start);
          anniversaryDate.setFullYear(year);
          const dateStr = anniversaryDate.toISOString().split('T')[0];
          
          // Only show up to current time + 1 year forecast
          // Calculate which anniversary it is
          const nth = year - startYear;
          
          if (nth > 0) {
              moments.push({
                  id: `park_anniversary_${tenant.id}_${year}`,
                  date: dateStr,
                  title: `入园 ${nth} 周年纪念`,
                  description: `感谢陪伴！${tenant.name} 加入园区已满 ${nth} 周年。`,
                  type: 'ParkAnniversary',
                  isAutoGenerated: true
              } as any);
          }
      }
      return moments;
  };

  // Combine stored moments with generated park moments
  const allMoments = selectedTenant 
      ? [...(selectedTenant.keyMoments || []), ...generateParkMoments(selectedTenant)].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime())
      : [];
  const timelineNodeClass = 'absolute -left-[9px] top-1 flex h-4 w-4 items-center justify-center rounded-full border shadow-sm backdrop-blur-xl transition-colors';
  const timelineNodeDotClass = 'h-1.5 w-1.5 rounded-full';

  return (
    <div className="liquid-glass-readable flex min-h-[320px] h-[calc(100dvh-10rem)] md:h-[calc(100vh-140px)] overflow-hidden rounded-[24px] min-w-0">
        {/* Left Sidebar: Tenant List */}
        <div className={`liquid-glass-toolbar w-full md:w-80 border-r border-white/65 flex flex-col min-w-0 ${showMobileList ? 'flex' : 'hidden md:flex'}`}>
            <div className="space-y-3 px-4 py-4">
                <h3 className="flex items-center gap-2 font-black text-slate-950">
                    <Sparkles size={18} className="text-blue-600"/> 客户洞察
                </h3>
                <div className="relative">
                    <Search className="absolute left-3 top-2.5 text-slate-500 w-4 h-4" />
                    <input 
                        type="text" 
                        placeholder="搜索客户..." 
                        className="liquid-elevated-field w-full rounded-2xl py-2 pl-9 pr-4 text-sm font-semibold text-slate-700 outline-none focus-visible:ring-4 focus-visible:ring-blue-500/15"
                        value={searchFilter}
                        onChange={e => setSearchFilter(e.target.value)}
                    />
                </div>
                <button 
                    onClick={handleBatchCollect}
                    disabled={isSearching}
                    className="liquid-action-strong liquid-pressable flex w-full items-center justify-center gap-2 rounded-full py-2 text-xs font-bold disabled:pointer-events-none disabled:opacity-50"
                >
                    {isSearching ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
                    {isSearching ? `正在更新... (${batchProgress?.current}/${batchProgress?.total})` : '一键更新全员动态'}
                </button>
            </div>
            <div className="flex-1 space-y-2 overflow-y-auto px-2 pb-3">
                {filteredTenants.map(t => (
                    <div 
                        key={t.id}
                        onClick={() => handleTenantSelect(t.id)}
                        className={`liquid-pressable cursor-pointer rounded-[18px] border-l-4 p-4 transition-colors ${selectedTenantId === t.id ? 'liquid-nav-active border-l-blue-600' : 'border-l-transparent hover:bg-white/55'}`}
                    >
                        <div className="min-w-0 break-words text-sm font-bold leading-snug text-slate-900" title={t.name}>{t.name}</div>
                        <div className="mt-1 flex min-w-0 flex-wrap items-center gap-2 text-xs text-slate-500">
                            <span className="min-w-0 truncate">{t.industry || '行业未录入'}</span>
                            <span className="h-1 w-1 shrink-0 rounded-full bg-slate-300/80"></span>
                            <span className="shrink-0">{parkDurationForTenant(t)}</span>
                        </div>
                    </div>
                ))}
                {filteredTenants.length === 0 && (
                    <div className="p-8 text-center text-xs font-semibold text-slate-500">未找到匹配客户</div>
                )}
            </div>
        </div>

        {/* Right Main: Details */}
        <div className={`flex-1 flex-col min-w-0 ${!showMobileList ? 'flex' : 'hidden md:flex'}`}>
            {selectedTenant ? (
                <>
                    {/* Header */}
                    <div className="liquid-glass-toolbar px-4 py-4 sm:px-6">
                        <div className="md:hidden mb-4">
                             <button onClick={() => setShowMobileList(true)} className="liquid-glass-control liquid-pressable flex items-center gap-1 rounded-full px-3 py-1.5 text-sm font-bold text-slate-600"><ArrowLeft size={16}/> 返回列表</button>
                        </div>
                        <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start">
                            <div>
                                <h2 className="flex flex-wrap items-center gap-2 text-xl font-black text-slate-950 sm:text-2xl">
                                    {selectedTenant.name}
                                    {selectedTenant.industry && <span className="liquid-glass-control rounded-full px-2.5 py-1 text-xs font-bold text-blue-700">{selectedTenant.industry}</span>}
                                </h2>
                                <div className="flex flex-wrap items-center gap-4 mt-3 text-sm text-slate-500">
                                    <div className="flex items-center gap-1.5" title="成立日期">
                                        <Cake size={16} className="text-pink-400"/>
                                        <span>成立: {selectedTenant.foundingDate || '未知'}</span>
                                    </div>
                                    <div className="flex items-center gap-1.5" title="入驻时长">
                                        <Building2 size={16} className="text-blue-400"/>
                                        <span>入驻: {calculateParkDuration(selectedTenant.moveInDate || selectedTenant.leaseStart)}</span>
                                    </div>
                                    <div className="flex items-center gap-1.5" title="法人代表">
                                        <User size={16} className="text-slate-500"/>
                                        <span>法人: {selectedTenant.legalRepName || '未知'}</span>
                                    </div>
                                </div>
                            </div>
                            <button className="liquid-glass-control liquid-pressable flex items-center justify-center gap-1 rounded-full px-3 py-2 text-sm font-bold text-blue-700"
                                onClick={() => setSingleUpdateNotice(true)}
                            >
                                <RefreshCw size={14}/> 更新动态
                            </button>
                        </div>
                        {singleUpdateNotice && (
                            <div className="liquid-glass-readable mt-4 flex flex-col gap-2 rounded-2xl border border-blue-200/70 px-3 py-2 text-sm font-semibold text-blue-800 sm:flex-row sm:items-center sm:justify-between">
                                <span>单个客户更新正在收口中。当前请使用左侧批量更新，系统会按筛选结果逐个采集并回写客户动态。</span>
                                <button
                                    type="button"
                                    onClick={() => setSingleUpdateNotice(false)}
                                    className="liquid-glass-control liquid-pressable self-start rounded-full px-3 py-1 text-xs font-black text-blue-700 sm:self-auto"
                                >
                                    知道了
                                </button>
                            </div>
                        )}
                    </div>

                    {/* Timeline Content */}
                    <div className="flex-1 overflow-y-auto space-y-6 p-4 sm:p-6">
                         {/* 时间轴 */}
                         {allMoments.length > 0 ? (
                             <div className="relative ml-4 space-y-8 border-l-2 border-blue-200/70 pb-8">
                                 {allMoments.map((moment, index) => (
                                     <div key={moment.id || index} className="relative pl-8 group">
                                         <div className={`${timelineNodeClass} border-blue-200/80 bg-white/72 group-hover:border-blue-500/80 group-hover:bg-blue-50/90`}>
                                             <span className={`${timelineNodeDotClass} bg-blue-500/80`} />
                                         </div>
                                         <div className="liquid-glass-readable liquid-pressable rounded-[20px] p-4 transition-all">
                                             <div className="mb-2 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                                                 <div className="flex min-w-0 flex-wrap items-center gap-2">
                                                     {getIconForType(moment.type as any)}
                                                     <span className="text-xs font-bold uppercase tracking-wider text-slate-500">{getTypeLabel(moment.type as any)}</span>
                                                     {moment.isAutoGenerated && <span className="liquid-glass-control rounded-full px-2.5 py-1 text-xs font-black text-slate-600">系统生成</span>}
                                                 </div>
                                                 <span className="liquid-glass-control shrink-0 self-start rounded-full px-2.5 py-1 text-xs font-black tabular-nums text-slate-600 sm:self-auto">{moment.date}</span>
                                             </div>
                                             <h4 className="mb-1 break-words text-lg font-black leading-snug text-slate-900">{moment.title}</h4>
                                             <p className="break-words text-sm leading-relaxed text-slate-700">{moment.description}</p>
                                             {moment.sourceUrl && (
                                                 <a href={moment.sourceUrl} target="_blank" rel="noopener noreferrer" className="liquid-glass-control liquid-pressable mt-3 inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold text-blue-700">
                                                     查看来源 <ExternalLink size={10} />
                                                 </a>
                                             )}
                                         </div>
                                     </div>
                                 ))}
                             </div>
                         ) : (
                             <div className="flex h-full min-h-[280px] flex-col items-center justify-center px-6 text-center text-slate-500">
                                 <div className="liquid-icon-well mb-4 flex h-16 w-16 items-center justify-center rounded-full text-blue-700">
                                     <Sparkles size={24}/>
                                 </div>
                                 <p className="text-base font-black text-slate-800">暂无动态记录</p>
                                 <p className="mt-1 text-xs font-semibold text-slate-500">点击左侧"更新全员动态"获取AI洞察</p>
                             </div>
                         )}

                         {/* 名称变更记录 */}
                         {(selectedTenant.nameHistory && selectedTenant.nameHistory.length > 0) && (
                             <div>
                                 <h3 className="flex items-center gap-2 text-sm font-bold text-slate-600 mb-3"><Edit2 size={16} className="text-amber-500"/> 名称变更记录</h3>
                                 <div className="relative border-l-2 border-amber-200/80 ml-4 space-y-4">
                                     {[...selectedTenant.nameHistory].reverse().map(r => (
                                         <div key={r.id} className="relative pl-8">
                                             <div className={`${timelineNodeClass} border-amber-300/80 bg-white/72`}>
                                                 <span className={`${timelineNodeDotClass} bg-amber-500/85`} />
                                             </div>
                                             <div className="liquid-glass-readable rounded-[18px] p-3 text-sm">
                                                 <div className="flex min-w-0 flex-wrap items-center gap-2 text-slate-600">
                                                     <span className="min-w-0 break-all text-slate-500 line-through">{r.oldName}</span>
                                                     <span className="font-black text-slate-500">→</span>
                                                     <span className="min-w-0 break-all font-black text-slate-800">{r.newName}</span>
                                                 </div>
                                                 <div className="mt-2 flex min-w-0 flex-wrap items-center gap-2 text-xs font-semibold text-slate-500">
                                                     <span className="liquid-glass-control rounded-full px-2 py-0.5 tabular-nums text-slate-600">{r.changedAt?.slice(0, 10)}</span>
                                                     {r.reason && <span className="min-w-0 break-words">· {r.reason}</span>}
                                                 </div>
                                             </div>
                                         </div>
                                     ))}
                                 </div>
                             </div>
                         )}

                         {/* 付款周期变更记录 */}
                         {(selectedTenant.paymentCycleChanges && selectedTenant.paymentCycleChanges.length > 0) && (
                             <div>
                                 <h3 className="flex items-center gap-2 text-sm font-bold text-slate-600 mb-3"><Repeat size={16} className="text-blue-500"/> 付款周期变更记录</h3>
                                 <div className="relative border-l-2 border-blue-200/80 ml-4 space-y-4">
                                     {[...selectedTenant.paymentCycleChanges].reverse().map(r => (
                                         <div key={r.id} className="relative pl-8">
                                             <div className={`${timelineNodeClass} border-blue-300/80 bg-white/72`}>
                                                 <span className={`${timelineNodeDotClass} bg-blue-500/85`} />
                                             </div>
                                             <div className="liquid-glass-readable rounded-[18px] p-3 text-sm">
                                                 <div className="flex min-w-0 flex-wrap items-center gap-2 text-slate-600">
                                                     <span className="font-semibold text-slate-500">{paymentCycleLabelMap[r.fromCycle] || r.fromCycle}</span>
                                                     <span className="font-black text-slate-500">→</span>
                                                     <span className="font-black text-slate-800">{paymentCycleLabelMap[r.toCycle] || r.toCycle}</span>
                                                 </div>
                                                 <div className="mt-2 flex min-w-0 flex-wrap items-center gap-2 text-xs font-semibold text-slate-500">
                                                     <span className="liquid-glass-control rounded-full px-2 py-0.5 tabular-nums text-slate-600">生效: {r.effectiveDate}</span>
                                                     {r.reason && <span className="min-w-0 break-words">· {r.reason}</span>}
                                                 </div>
                                             </div>
                                         </div>
                                     ))}
                                 </div>
                             </div>
                         )}
                    </div>
                </>
            ) : (
                <div className="liquid-glass-readable flex h-full flex-col items-center justify-center px-6 text-center text-sm font-semibold text-slate-500">
                    <Building2 size={48} className="mb-4 text-slate-500 opacity-80" />
                    <p>请选择一个客户查看详细洞察</p>
                </div>
            )}
        </div>
    </div>
  );
};
